# Generated by Django 2.1.2 on 2018-11-04 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0002_auto_20181104_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='upperCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ProductManager.Category'),
        ),
    ]
