# Generated by Django 2.1.2 on 2018-12-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductManager', '0006_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaialableAmt',
            new_name='availableAmt',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='C:\\Users\\Konrad\\Documents\\Projects\\VSCode\\ecommerce\\ecommerce\\static\\img'),
        ),
    ]
